### ISSUE TITLE
Buttons for downloading passwords

### ISSUE THREAD

**Issue by piechowiakmichal** [many-passwords/many-passwords.github.io#20]
Hi!

I think a button for downloading passwords will be useful. 

I prepared visualizations:

![buttons](https://user-images.githubusercontent.com/36797326/140730478-708ce1c5-90a9-4c8f-b7c5-41f7ae791374.png)

The first button would download csv, second button would download json, third would redirect to the main repository and showed the number of collected passwords (this is also used in the About Us section).

Please write if you want to be assigned with it, thanks!

**Comment by NgoQuocBao1010** [comment]
Hello, I believe I can help with this issue. Can you assign me to it?

**Comment by piechowiakmichal** [comment]
Hi, of course. I assigned you, thanks!
