### ISSUE TITLE
New color scheme

### ISSUE THREAD

**Issue by ABarpanda** [many-passwords/many-passwords.github.io#29]
![image](https://github.com/many-passwords/many-passwords.github.io/assets/145291762/09cc8454-2be3-4b5f-ab5c-cccabeb7f41a)
![image](https://github.com/many-passwords/many-passwords.github.io/assets/145291762/9e3ec7a4-e3d0-4f54-8800-4138e0e94956)
![image](https://github.com/many-passwords/many-passwords.github.io/assets/145291762/cbe11c6d-454b-41dd-beb7-3e6b1361f703)
How about this color scheme for the whole website?

![image](https://github.com/many-passwords/many-passwords.github.io/assets/145291762/78a7c4b9-6225-4d61-9e92-e179ffcb3951)
And these colors for the loading part? 
I think these colors match more to the overall theme instead of red, orange, and yellow. 

I am also planning on adding a webpage for contribution, instead of redirecting it to GitHub. What do you think?
@many-passwords

**Comment by piechowiakmichal** [comment]
Hi! I think that current look is more readable. I think also that redirection to Github to [CONTRIBUTING.md](https://github.com/many-passwords/many-passwords/blob/main/CONTRIBUTING.md) is better, but thanks! Have a nice day!

**Comment by ABarpanda** [comment]
I personally felt that the website was looking very dull and repulsive. That's why I tried to make the website more lively. Anyways, thanks for the reply.
