### ISSUE TITLE
Adding a contact form

### ISSUE THREAD

**Issue by piechowiakmichal** [many-passwords/many-passwords.github.io#7]
There is no form of contact on the website. The contact is needed for users not using Github.

I was thinking about a form that can be navigated to with navbar.

Write below if you want to do so, thanks!

**Comment by rahulbhatt1899** [comment]
Hey, I would like to contribute to this issue.

**Comment by piechowiakmichal** [comment]
Fine, I think about contact form in new card linked in navbar. 

Something like that:

![image](https://user-images.githubusercontent.com/36797326/135892631-6230ac18-3559-4c65-8a47-1d2ebf5345a7.png)

It's great if the user can get a copy a question. Can you do something like that?

**Comment by rahulbhatt1899** [comment]
Sure, I can give it a go!

**Comment by piechowiakmichal** [comment]
I assigned you, thanks!

**Comment by rahulbhatt1899** [comment]
Do you like this design?
![image](https://user-images.githubusercontent.com/35606353/135898040-4f91d912-c01b-46e9-8475-bbde7cdc95ea.png)

**Comment by piechowiakmichal** [comment]
Looks very good! I think it's worth adding navbar and it will be great.

**Comment by rahulbhatt1899** [comment]
> Looks very good! I think it's worth adding a navbar and it will be great.

Navbar is there I guess the form size is too large, will update and add here.

**Comment by piechowiakmichal** [comment]
It's good if it only takes up a full page and no scrolling is needed.

**Comment by rahulbhatt1899** [comment]
![image](https://user-images.githubusercontent.com/35606353/135900563-c0d76c4b-8d84-4360-a72e-3f2e7886a233.png)
Should I push this?

**Comment by piechowiakmichal** [comment]
Looks perfect! Of cource, push it.

**Comment by rahulbhatt1899** [comment]
#8 Added PR please check and suggest if there is any feedback.
